crud/urls.py

from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud_main.urls')),
    path('crud_main', include('crud_main.urls')),
    path('', TemplateView.as_view(template_name='get_data.html'), name='dataView'),
]

crud_main/urls.py
from django.urls import path
from . import views

app_name = 'crud_main'
urlpatterns = [

    path('', views.getData, name = "dataView"),

    path('create_server', views.create_server, name="create_server"),
    path('create_type_of_server', views.itype_of_server, name="type_of_server"),
    path('users', views.iusers, name='users'),
    path('servers', views.iservices, name='servers'),
    path('applications', views.iapplications, name="applications"),
    path('apphasservices', views.iapphasservices, name= "apphasservices"),
    path('overall', views.ioverall, name = "overall"),


    path('update_server/<server_id>', views.update_server, name = "update_server"),
    path('update_type_of_server/<type_of_server_id>', views.update_type_of_server, name = "update_type_of_server"),
    path('update_users/<users_id>', views.update_users, name = "update_users"),
    path('update_services/<services_id>', views.update_services, name = "update_servers"),
    path('update_applications/<applications_id>', views.update_applications, name = "update_applications"),
    path('update_app_has_services/<apphasservices_id>', views.updateapphasservices, name= "update_app_has_services" ),
    path('update_overall/<overall_id>', views.update_overall, name = "update_overall"),


    path('delete_server/<str:pk>', views.deleteServer, name="delete_server"),
    path('delete_type_of_server/<str:pk>', views.deleteTypeofserver, name="delete_type_of_server"),
    path('delete_users/<str:pk>', views.deleteUsers, name="delete_users"),
    path('delete_services/<str:pk>', views.deleteServices, name="delete_servers"),
    path('delete_applications/<str:pk>', views.deleteApplications, name="delete_applications"),
    path('delete_app_has_services/<str:pk>', views.deleteapphasservices, name = "delete_app_has_services"),
    path('delete_overall/<str:pk>', views.deleteOverall, name="delete_overall"),


    path('list/', views.list, name = "list"),

    path('search/', views.search, name="Search"),

    path('show_server/<server_id>', views.show_server, name="show_server"),
    ]

crud_main/models.py
from django.db import models
import uuid

# To Understand the Relation Check the image.jpeg file in the Root + docs Directory of the project
# sterven4/docs/image.jpeg


class type_of_server(models.Model):
    type_server_id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    server_type = models.CharField(max_length=45)
    description = models.CharField(max_length=45)
    class Meta:
        ordering = ["type_server_id"]
        verbose_name_plural = "types_of_server"

    def __str__(self):
        return self.server_type

class server(models.Model):
    server_id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    name = models.CharField(max_length=45)
    type_of_server = models.ForeignKey(type_of_server, on_delete=models.CASCADE)
    processor_number = models.CharField(max_length=45, blank=False)
    memory_capacity = models.CharField(max_length=45)
    storage_capacity = models.CharField(max_length=45)
    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Servers"

    def __str__(self):
        return self.name

class application(models.Model):
    app_id = models.UUIDField(default=uuid.uuid4, unique=True, blank=False, primary_key=False, editable=False)
    name_app = models.CharField(max_length=45)
    logo_app = models.ImageField(null = True, blank = True)
    server = models.ForeignKey(server, on_delete=models.CASCADE)
    user = models.ForeignKey("user", on_delete=models.CASCADE)
    class Meta:
        ordering = ["name_app"]
        verbose_name_plural = "Apps"

    def __str__(self):
        return self.name_app

class user(models.Model):
    user_id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    user_name = models.CharField(max_length=45)
    sur_name = models.CharField(max_length=45)
    email = models.EmailField()
    class Meta:
        ordering = ["user_id"]
        verbose_name_plural = "Users"

    def __str__(self):
        return self.user_name

class services(models.Model):
    service_id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    name_of_service = models.CharField(max_length=45)
    date_of_launch = models.DateField()
    memory_used = models.CharField(max_length=45)
    ram_memory = models.CharField(max_length=45)
    service_launched_onto = models.ForeignKey(server, on_delete=models.CASCADE)
    class Meta:
        ordering = ["service_id"]
        verbose_name_plural = "Services"

    def __str__(self):
        return self.name_of_service

class applicaitonshasservices(models.Model):
    app_id = models.ForeignKey(application, blank = False, on_delete=models.CASCADE)
    services_id = models.ForeignKey(services, blank = False, on_delete=models.CASCADE)
    class Meta:
        ordering = ["app_id"]
        verbose_name_plural = "AppsHasService"
    def __int__(self):
        return self.app_id

class overall(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    number_of_server_used = models.IntegerField()
    total_storage_used = models.IntegerField()
    class Meta:
        ordering = ["number_of_server_used"]
        verbose_name_plural = "Overall"
    

crud_main/forms.py
from django import forms
from django.forms import ModelForm

from .models import server, type_of_server,user, services,application, applicaitonshasservices, overall

class DateInput(forms.DateInput):
    input_type = 'date'

class serverForm(ModelForm):
    class Meta:
        model = server
        fields = '__all__'

class type_of_serverForm(ModelForm):
    class Meta:
        model = type_of_server
        fields = '__all__'
class usersForm(ModelForm):
    class Meta:
        model = user
        fields = '__all__'

class serviceForm(ModelForm):
    class Meta:
        model = services
        fields = '__all__'
        widgets = {
            'date_of_launch': DateInput(),
        }

class applicationsForm(ModelForm):
    class Meta:
        model = application
        fields = '__all__'

class apphasservicesForm(ModelForm):
    class Meta:
        model = applicaitonshasservices
        fields = '__all__'

class overallForm(ModelForm):
    class Meta:
        model = overall
        fields = '__all__'

crud_main/views.py
from django.shortcuts import redirect, render
from .models import server, type_of_server,user, application, services,applicaitonshasservices, overall
from .forms import serverForm,type_of_serverForm,usersForm,serviceForm,applicationsForm,overallForm,apphasservicesForm


def getData(request):
    return render(request, 'crud_main/get_data.html')


def create_server(request):
    form = serverForm()
    if request.method == 'POST':
        form = serverForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crud_main:dataView')
    context = {'form':form}
    return render(request,'crud_main/create_server.html', context)


def itype_of_server(request):
    form = type_of_serverForm()
    if request.method == 'POST':
        form = type_of_serverForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crud_main:dataView')
    context = {'form':form}
    return render(request,'crud_main/type_of_server.html', context)

    
def iusers(request):
    form = usersForm()
    if request.method == 'POST':
        form = usersForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crud_main:dataView')
    context = {'form':form}
    return render(request,'crud_main/users.html', context)


def iservices(request):
    form = serviceForm()
    if request.method == 'POST':
        form = serviceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crud_main:dataView')
    context = {'form':form}
    return render(request,'crud_main/servers.html', context)


def iapphasservices(request):
    form = apphasservicesForm()
    if request.method == 'POST':
        form = apphasservicesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crud_main:dataView')
    context = {'form':form}
    return render(request,'crud_main/app_has_services.html', context)


def iapplications(request):
    form = applicationsForm()
    if request.method == 'POST':
        form = applicationsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crud_main:dataView')
    context = {'form':form}
    return render(request,'crud_main/applications.html', context)
    

def ioverall(request):
    form = overallForm()
    if request.method == 'POST':
        form = overallForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crud_main:dataView')
    context = {'form':form}
    return render(request,'crud_main/overall.html', context)



def update_server(request, server_id):
    updateObject = server.objects.get(pk=server_id)
    form = serverForm(request.POST or None, instance=updateObject)
    if form.is_valid():
        form.save()
        return redirect('crud_main:list')
    return render(request, 'crud_main/update_server.html', {'updateObject':updateObject, 'form':form} )


def update_type_of_server(request, type_of_server_id):
    updateObject = type_of_server.objects.get(pk=type_of_server_id)
    form = type_of_serverForm(request.POST or None, instance=updateObject)
    if form.is_valid():
        form.save()
        return redirect('crud_main:list')
    return render(request, 'crud_main/update_type_of_server.html', {'updateObject':updateObject, 'form':form} )


def update_users(request, users_id):
    updateObject = user.objects.get(pk=users_id)
    form = usersForm(request.POST or None, instance=updateObject)
    if form.is_valid():
        form.save()
        return redirect('crud_main:list')
    return render(request, 'crud_main/update_users.html', {'updateObject':updateObject, 'form':form} )

def update_services(request, services_id):
    updateObject = services.objects.get(pk=services_id)
    form = serviceForm(request.POST or None, instance=updateObject)
    if form.is_valid():
        form.save()
        return redirect('crud_main:list')
    return render(request, 'crud_main/update_services.html', {'updateObject':updateObject, 'form':form} )


def update_applications(request, applications_id):
    updateObject = application.objects.get(pk=applications_id)
    form = applicationsForm(request.POST or None, instance=updateObject)
    if form.is_valid():
        form.save()
        return redirect('crud_main:list')
    return render(request, 'crud_main/update_applications.html', {'updateObject':updateObject, 'form':form} )


def updateapphasservices(request, apphasservices_id):
    updateObject = applicaitonshasservices.objects.get(pk=apphasservices_id)
    form = apphasservicesForm(request.POST or None, instance=updateObject)
    if form.is_valid():
        form.save()
        return redirect('crud_main:list')
    return render(request, 'crud_main/updateapphasservices.html', {'updateObject':updateObject, 'form':form} )


def update_overall(request, overall_id):
    updateObject = overall.objects.get(pk=overall_id)
    form = overallForm(request.POST or None, instance=updateObject)
    if form.is_valid():
        form.save()
        return redirect('crud_main:list')
    return render(request, 'crud_main/update_overall.html', {'updateObject':updateObject, 'form':form} )

    

def deleteServer(request,pk):
    serverObject = server.objects.get(server_id = pk)
    if request.method == 'POST':
        serverObject.delete()
        return redirect('crud_main:dataView')
    context = {'object':serverObject}
    return render(request, 'crud_main/delete_template_server.html', context)


def deleteTypeofserver(request,pk):
    serverObject = type_of_server.objects.get(type_server_id = pk)
    if request.method == 'POST':
        serverObject.delete()
        return redirect('crud_main:dataView')
    context = {'object':serverObject}
    return render(request, 'crud_main/delete_template_type_of_server.html', context)


def deleteUsers(request,pk):
    serverObject = user.objects.get(user_id = pk)
    if request.method == 'POST':
        serverObject.delete()
        return redirect('crud_main:dataView')
    context = {'object':serverObject}
    return render(request, 'crud_main/delete_template_users.html', context)


def deleteServices(request,pk):
    serverObject = services.objects.get(service_id = pk)
    if request.method == 'POST':
        serverObject.delete()
        return redirect('crud_main:dataView')
    context = {'object':serverObject}
    return render(request, 'crud_main/delete_template_servers.html', context)


def deleteApplications(request,pk):
    serverObject = application.objects.get(app_id = pk)
    if request.method == 'POST':
        serverObject.delete()
        return redirect('crud_main:dataView')
    context = {'object':serverObject}
    return render(request, 'crud_main/delete_template_apphasservices.html', context)

def deleteapphasservices(request, pk):
    serverObject = applicaitonshasservices.objects.get(app_id = pk)
    if request.method == 'POST':
        serverObject.delete()
        return redirect('crud_main:dataView')
    context = {'object':serverObject}
    return render(request, 'crud_main/delete_template_applications.html', context)


def deleteOverall(request,pk):
    serverObject = overall.objects.get(id = pk)
    if request.method == 'POST':
        serverObject.delete()
        return redirect('crud_main:dataView')
    context = {'object':serverObject}
    return render(request, 'crud_main/delete_template_overall.html', context)



def list (request):
    serverlist = server.objects.all()
    type_of_serverlist = type_of_server.objects.all()
    userslist = user.objects.all()
    serverslist = services.objects.all()
    applicationslist = application.objects.all()
    applicationhasservices = applicaitonshasservices.objects.all()
    overalllist = overall.objects.all()
    context = {'server':serverlist,'type_of_server':type_of_serverlist,'users':userslist,'servers':serverslist,'applications':applicationslist,'applicationshasservices':applicationhasservices,'overall':overalllist}
    return render(request, 'crud_main/list.html', context)



def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        server = server.objects.filter(name__contains=searched)

        return render(request,'crud_main/search.html',{'searched': searched, 'server': server})
    else:
        return render(request, 'crud_main/search.html',{})

def show_server(request, server_id):
    serv = server.objects.get(pk=server_id)
    return render(request, 'crud_main/show_server.html',{'serv': serv})

crud_main/templates/crud_main/delete_template_apphasservices.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST" class="lol">
        {% csrf_token %}
        <p>Are you Want to delete "{{object}}"</p>
        <a href="{% url 'crud_main:dataView' %}" class="btn btn-primary">Go Back
        </a>
        <input type="submit" value="confirm" />
    </form>
    {% endblock %}

crud_main/templates/crud_main/delete_template_applications.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you Want to delete "{{object}}"</p>
        <a href="{% url 'crud_main:dataView' %}">Go Back
        </a>
        <input type="submit" value="confirm" />
    </form>
    {% endblock %}

crud_main/templates/crud_main/delete_template_overall.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST" class="lol">
        {% csrf_token %}
        <p class="popy">Are you Want to delete "{{object}}"</p>
        <a href="{% url 'crud_main:dataView' %}">Go Back</a>
        <input type="submit" value="confirm" />
    </form>
    {% endblock %}

crud_main/templates/crud_main/delete_template_server.html
{% extends "base.html" %}

{% block content %}
<form action="" method="POST">
        {% csrf_token %}
        <p>Are you Want to delete "{{object}}"</p>
        <a href="{% url 'crud_main:dataView' %}">Go Back
        </a>
        <input type="submit" value="confirm" />
    </form>
    {% endblock %}

crud_main/templates/crud_main/delete_template_servers.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you Want to delete "{{object}}"</p>
        <a href="{% url 'crud_main:dataView' %}">Go Back
        </a>
        <input type="submit" value="confirm" />
    </form>
    {% endblock %}

crud_main/templates/crud_main/delete_template_users.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you Want to delete "{{object}}"</p>
        <a href="{% url 'crud_main:dataView' %}">Go Back
        </a>
        <input type="submit" value="confirm" />
    </form>
    {% endblock %}

crud_main/templates/crud_main/overall.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="lol">
        <center>
            <section class="tete">
                <h3>Add Overall</h3>
            </section>
        </center>
        
            </br>
            <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-sm-4 col-md-10">
                            {{ form.number_of_server_used|as_crispy_field }}
                        </div><br>
                        <div class="form-group col-sm-4 col-md-10">
                            {{ form.total_storage_used|as_crispy_field }}
                        </div><br>
                    </div>
                <br></br>
                <button type="submit" class="btn btn-success">Add Overall</button>
            </form>
        
        </div>
    {% endblock %}

crud_main/templates/crud_main/search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% if searched %}

<div class="search-title" >
                <h2>You searched for: {{ searched }}</h2>
</div>
</br>

<div class="article-table">
    <table class="table table-light table-striped table-bordered">
      <thead>
        <tr class="table-dark">
          <th class="table-top" scope="col">Server Name</th>
          <th class="table-top" scope="col">Type</th>
          <th class="table-top" scope="col">Processor Number</th>
          <th class="table-top" scope="col">Memory Capacity</th>
          <th class="table-top" scope="col">Storage Capacity</th>
          <th class="table-top text-end" scope="col"></th>
        </tr>
      </thead>
      {% for search in server %}
      <tr>
        <td class="table-bot">{{ search.name}}</a></td>
        <td class="table-bot">{{ search.type_of_server }}</td>
        <td class="table-bot">{{ search.processor_number }}</td>
        <td class="table-bot">{{ search.memory_capacity }}</td>
        <td class="table-bot">{{ search.storage_capacity }}</td>
        <td class="table-top text-end">
          <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <a href="{% url 'crud_main:update_server' list.server_id %}" type="button" class="btn btn-outline-primary btn-sm"> Update </a>
            <a href="{% url 'crud_main:delete_servers' list.server_id %}" type="button" class="btn btn-danger btn-sm"> Delete </a>
          </div>
        </td>
      </tr>
    </table>
</div>
        {% endfor %}

        {% else %}
            <section class="search-title-2">
                <h2> T'as oublié de chercher une oeuvre</h2>
            </section>
        {% endif %}
{% endblock %}

crud_main/templates/crud_main/show_server.html
{% extends 'base.html' %}


{% block content %}

<div class="desc">
    <h2 class="des">SERVER DESCRIPTION</h2>
    <br></br>
    <ul>
    {% for server in show_server %}

        <div class="card">
          <div class="card-header bg-danger p-2 text-white bg-opacity-50">
            {{ server }}
          </div>
          <div class="card-body">
            <ul>
                <li><strong>Name:</strong> {{server.name}}</li>
                <li><strong>Server type:</strong> {{server.type_of_server}}</li>
                <li><strong>Number of processor:</strong> {{server.processor_number}}</li>
                <li><strong>Memory capacity:</strong> {server.memory_capacity}}</li>
                <li><strong>Storage capacity:</strong> {{server.storage_capacity}}</li>
                <p> </p>
            </ul>

          </div>
        </div>

        <br></br>

    {% endfor %}
    </ul>
</div>

{% endblock %}

crud_main/templates/crud_main/type_of_server.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="lol">
    <center>
        <section class="tete">
            <h3>Add Server type</h3>
        </section>
    </center>
    
        </br>
        <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-sm-4 col-md-10">
                        {{ form.server_type|as_crispy_field }}
                    </div><br>

                    <div class="form-group col-sm-4 col-md-10">
                        {{ form.description|as_crispy_field }}
                    </div><br>
                </div>

            <br></br>
            <button type="submit" class="btn btn-success">Add app has service</button>
        </form>
</div>
    {% endblock %}

crud_main/templates/crud_main/update_applications.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="lol">
    <center>
        <section class="tete">
            <h3> Update the application {{application}} </h3>
        </section>
    </center>

    </br>

    <form action="" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.name_app|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.logo_app|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.server|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.user|as_crispy_field }}
                </div>
            </div>


        <br></br>
        <input class="btn btn-success" type="submit" value="Update the server">
        <a class="btn btn-outline-danger" href="{% url 'crud_main:list' %}">Annuler</a>

    </form>

</div>

{% endblock %}

crud_main/templates/crud_main/update_services.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="lol">
    <center>
        <section class="tete">
            <h3> Update the service {{services}}</h3>
        </section>
    </center>
    </br>

    <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.name_of_service|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.date_of_launch|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.memory_used|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.ram_memory|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.service_launched_onto|as_crispy_field }}
                </div>
            </div>

        <br></br>
        <input class="btn btn-success" type="submit" value="Update the server">
        <a class="btn btn-outline-danger" href="{% url 'crud_main:list' %}">Annuler</a>

    </form>

</div>

{% endblock %}

crud_main/templates/crud_main/update_type_of_server.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="lol">
    <center>
        <section class="tete">
            <h3>Update the server type: {{type_of_server}}</h3>
        </section>
    </center>
    </br>

    <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.server_type|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.description|as_crispy_field }}
                </div>
            </div>

        <br></br>
        <input class="btn btn-success" type="submit" value="Update the server">
        <a class="btn btn-outline-danger" href="{% url 'crud_main:list' %}">Annuler</a>

    </form>

</div>

{% endblock %}

crud_main/templates/crud_main/update_users.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="lol">
    <center>
        <section class="tete">
            <h3>Update the user: {{user}}</h3>
        </section>
    </center>

    </br>

    <form action="" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.user_name|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.sur_name|as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-sm-6 col-md-10">
                    {{ form.email|as_crispy_field }}
                </div>
            </div>

        <br></br>
        <input class="btn btn-success" type="submit" value="Update the server">
        <a class="btn btn-outline-danger" href="{% url 'crud_main:list' %}">Annuler</a>

    </form>

</div>

{% endblock %}