crud/urls.py

from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud_main.urls')),
    path('crud_main', include('crud_main.urls')),
    path('', TemplateView.as_view(template_name='get_data.html'), name='dataView'),
]

crud_main/urls.py
from django.urls import path
from . import views

app_name = 'crud_main'
urlpatterns = [

    path('', views.getData, name = "dataView"),

    path('create_server', views.create_server, name="create_server"),
    path('create_type_of_server', views.itype_of_server, name="type_of_server"),
    path('users', views.iusers, name='users'),
    path('servers', views.iservices, name='servers'),
    path('applications', views.iapplications, name="applications"),
    path('apphasservices', views.iapphasservices, name= "apphasservices"),
    path('overall', views.ioverall, name = "overall"),


    path('update_server/<server_id>', views.update_server, name = "update_server"),
    path('update_type_of_server/<type_of_server_id>', views.update_type_of_server, name = "update_type_of_server"),
    path('update_users/<users_id>', views.update_users, name = "update_users"),
    path('update_services/<services_id>', views.update_services, name = "update_servers"),
    path('update_applications/<applications_id>', views.update_applications, name = "update_applications"),
    path('update_app_has_services/<apphasservices_id>', views.updateapphasservices, name= "update_app_has_services" ),
    path('update_overall/<overall_id>', views.update_overall, name = "update_overall"),


    path('delete_server/<str:pk>', views.deleteServer, name="delete_server"),
    path('delete_type_of_server/<str:pk>', views.deleteTypeofserver, name="delete_type_of_server"),
    path('delete_users/<str:pk>', views.deleteUsers, name="delete_users"),
    path('delete_services/<str:pk>', views.deleteServices, name="delete_servers"),
    path('delete_applications/<str:pk>', views.deleteApplications, name="delete_applications"),
    path('delete_app_has_services/<str:pk>', views.deleteapphasservices, name = "delete_app_has_services"),
    path('delete_overall/<str:pk>', views.deleteOverall, name="delete_overall"),


    path('list/', views.list, name = "list"),

    path('search/', views.search, name="Search"),

    path('show_server/<server_id>', views.show_server, name="show_server"),
    ]

templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Servers</title>
    <link rel="stylesheet" href="{% static 'lol.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #231F20;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'crud_main:dataView' %}" >Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crud_main:list' %}">List</a>
            </li>

          </ul>

          <form class="d-flex" role="search" method=POST action="">

              {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="search server" aria-label="Search" name="searched">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
          </form>

        </div>
      </div>
    </nav>


        {% block title %}
        {% endblock %}

        {% block content %}
        {% endblock %}


<footer></footer>
<div class="footer">
  <p>Server administration</p>
</div>

</footer>

</body>
</html>